name: Sync Markdown
on:
  push:
    paths:
      - 'markdown/_posts/​**​'
      - '!​**.js'
concurrency: 
  group: sync-articles-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 处理Markdown
        run: |
          # 你的现有脚本...
      - name: 提交更改
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add my-blog/articles/
          git commit -m "自动添加新文章 [skip ci]" || exit 0
          git push